### ISSUE TITLE
Compile Error with Windows Universal App

### ISSUE THREAD

**Issue by mutzl** [Fody/PropertyChanged#126]
When trying to compile a **Windows 10 Universal App** (VS 2015 RC) with PropertyChanged.Fody, I get the following error:
>Fody: An unhandled exception occurred:
Exception:
Unknown custom metadata item kind: 6
StackTrace:
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits) in c:\Code\cecil\symbols\pdb\Microsoft.Cci.Pdb\PdbFunction.cs:line 359
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits) in c:\Code\cecil\symbols\pdb\Microsoft.Cci.Pdb\PdbFunction.cs:line 270
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings) in c:\Code\cecil\symbols\pdb\Microsoft.Cci.Pdb\PdbFunction.cs:line 136
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader) in c:\Code\cecil\symbols\pdb\Microsoft.Cci.Pdb\PdbFile.cs:line 273
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid) in c:\Code\cecil\symbols\pdb\Microsoft.Cci.Pdb\PdbFile.cs:line 382
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions() in c:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\PdbReader.cs:line 94
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header) in c:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\PdbReader.cs:line 75
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader() in c:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 786
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader) in c:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 859
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) in c:\Code\cecil\Mono.Cecil\AssemblyReader.cs:line 108
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters) in c:\Code\cecil\Mono.Cecil\AssemblyReader.cs:line 83
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters) in c:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 890
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in c:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 874
   at InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\ModuleReader.cs:line 16
   at InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\InnerWeaver.cs:line 25
Source:
Mono.Cecil.Pdb
TargetSite:
Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)		

But it works well for a Windows 10 Universal **Lilbrary**.

Visual Studio Enterprise 2015 RC (V 14.0.22823.1)
Windows 10 Pro Insider Preview (Build 10074)

**Comment by distantcam** [comment]
Update the fody package to the latest should fix the problem.

**Comment by mutzl** [comment]
You are absolutely right. Thanks!!

(Just as a side note: I installed PropertyChanged.Fody via NuGet, which added Fody version **1.13.0** to my project, while 1.28.3 is currently the latest.)

**Comment by SimonCropp** [comment]
@mutzl yeah nuget adding the lowest dependency version is something the nuget team refuses to fix. So very time u do a nuget install u need to nuget update to fix all the incorrect dependecy versions it has brought in. Sorry about the confusion
