### ISSUE TITLE
Fody.PropertyChanged having issues locating Mono.Cecil v0.9.5

### ISSUE THREAD

**Issue by framgeld** [Fody/PropertyChanged#170]
Hi,

Not sure why, but one of our developer's is not able to build our Visual Studio 2013 solution (C# projects) that make use of Fody.PropertyChanged (everyone else can build without issue). He is getting the following exception:

```
error : Could not load type 'Mono.Cecil.Cil.InstructionRange' from assembly 'Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. 
error : StackTrace:
error :    at Mono.Cecil.Pdb.PdbReader.Read(MethodBody body, InstructionMapper mapper)
error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody() 
error :    at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method) 
error :    at Mono.Cecil.MethodDefinition.<get_Body>b__2(MethodDefinition method, MetadataReader reader) 
error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read) 
error :    at Mono.Cecil.MethodDefinition.get_Body() 
error :    at ModuleWeaver.GetSingleField(PropertyDefinition property, Code code, MethodDefinition methodDefinition) in c:\TeamCity\buildAgent\work\eaa0f905cc364117\PropertyChanged.Fody\MappingFinder.cs:line 78 
error :    at ModuleWeaver.GetSingleField(PropertyDefinition property) in c:\TeamCity\buildAgent\work\eaa0f905cc364117\PropertyChanged.Fody\MappingFinder.cs:line 64 
error :    at ModuleWeaver.TryGetField(TypeDefinition typeDefinition, PropertyDefinition property) in c:\TeamCity\buildAgent\work\eaa0f905cc364117\PropertyChanged.Fody\MappingFinder.cs:line 44 
error :    at ModuleWeaver.<GetMappings>d__9c.MoveNext() in c:\TeamCity\buildAgent\work\eaa0f905cc364117\PropertyChanged.Fody\MappingFinder.cs:line 22 
error :    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) 
error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) 
error :    at ModuleWeaver.FindMappings(List`1 notifyNodes) in c:\TeamCity\buildAgent\work\eaa0f905cc364117\PropertyChanged.Fody\MappingFinder.cs:line 13 
error :    at ModuleWeaver.Execute() in c:\TeamCity\buildAgent\work\eaa0f905cc364117\PropertyChanged.Fody\ModuleWeaver.cs:line 33 
error :    at lambda_method(Closure , Object ) 
error :    at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144 
error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
```

The Mono.Cecil assemblies contained within his instance of the package folders are identical to those in my instance of the package folders.

I have tried copying the Mono.Cecil assemblies into all of the package folders where a Fody or a Fody.PropertyChanged assembly exists, and this does not fix it. Nor does running Visual Studio as local administrator.

Has anybody had any experience with this issue?

Thanks in advance for any help you can provide.

**Comment by framgeld** [comment]
This is using the following versions:

- v1.28.3 of Fody
- v1.50.1 of PropertyChanged.Fody

**Comment by SimonCropp** [comment]
can u try the latest versions. and if it still happens can u upload a repro

**Comment by SimonCropp** [comment]
closed due to no response
