### ISSUE TITLE
Unhandled Exception with VS 2010 and VB

### ISSUE THREAD

**Issue by NeilMJohnson** [Fody/PropertyChanged#177]
I added the ImplementPropertyChanged attribute on two of my Entity Framework classes and tried to compile them and got the following error:
Error	1	Fody: An unhandled exception occurred:
Exception:
Unable to obtain public key for StrongNameKeyPair.
StackTrace:
   at System.Reflection.StrongNameKeyPair.ComputePublicKey()
   at System.Reflection.StrongNameKeyPair.get_PublicKey()
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 85
Source:
mscorlib
TargetSite:
Byte[] ComputePublicKey()
	DataModels

The project does have a StrongNameKey associated with it in a .pfx file.  All of the projects in the solution have StrongNameKeys so I cannot remove the key from this project.  Am I missing something in the configuration for this add-on? I have just downloaded the most recent version of PropertyChanged as of this date.  Is this more of a Fody issue than with your extension?

**Comment by NeilMJohnson** [comment]
Simon, this seems to be more of a Fody Issue than with your extension.  I am going to close it and add it to the Fody issues.  I was really looking forward to using your extension, it looks like it will save me a lot of coding.  Thanks.
