### ISSUE TITLE
method not found

### ISSUE THREAD

**Issue by apobekiaris** [Fody/PropertyChanged#189]
I get this exception inside VS but only on my buildserver. 

`1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Method not found: 'Mono.Cecil.MethodReference Mono.Cecil.ModuleDefinition.ImportReference(Mono.Cecil.MethodReference)'.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at ModuleWeaver.FindCoreReferences()
1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 26
1>MSBUILD : error :    at lambda_method(Closure , Object )
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : PropertyChanged.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void FindCoreReferences()
1>MSBUILD : error : 
`

**Comment by apobekiaris** [comment]
can't repro it anymore after installing VS update 3
