### ISSUE TITLE
Crash on pcl 

### ISSUE THREAD

**Issue by xalikoutis** [Fody/PropertyChanged#200]
Just updated to 1.52.0 and my pcl project will crash on built.
1.51.3 works just fine

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Fody: An unhandled exception occurred:
> Exception:
> Object reference not set to an instance of an object.
> StackTrace:
>    at EqualityCheckWeaver.InjectEqualityCheck(Instruction targetInstruction, TypeReference targetType) in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 92
>    at EqualityCheckWeaver.CheckAgainstProperty() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 47
>    at EqualityCheckWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 28
>    at ModuleWeaver.ProcessTypes(List`1 notifyNodes) in C:\projects\propertychanged\PropertyChanged.Fody\TypeProcessor.cs:line 38
>    at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 43
>    at lambda_method(Closure , Object )
>    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
>    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
> Source:
> PropertyChanged.Fody
> TargetSite:
> Void InjectEqualityCheck(Mono.Cecil.Cil.Instruction, Mono.Cecil.TypeReference)	ThesisSFA

**Comment by SimonCropp** [comment]
@distantcam thoughts?

**Comment by dtoth1** [comment]
hello,

very similar issue comes here too after upgrading to 1.52.0 (universal win project):

Severity	Code	Description	Project	File	Line
Error		Fody: An unhandled exception occurred:
Exception:
Object reference not set to an instance of an object.
StackTrace:
   at EqualityCheckWeaver.InjectEqualityCheck(Instruction targetInstruction, TypeReference targetType) in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 92
   at EqualityCheckWeaver.CheckAgainstField() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 39
   at EqualityCheckWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 32
   at ModuleWeaver.ProcessTypes(List`1 notifyNodes) in C:\projects\propertychanged\PropertyChanged.Fody\TypeProcessor.cs:line 38
   at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 43
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
PropertyChanged.Fody
TargetSite:
Void InjectEqualityCheck(Mono.Cecil.Cil.Instruction, Mono.Cecil.TypeReference)	CryptTalkIVR_UWP_raw

**Comment by sebandraos** [comment]
Won't bog down the thread with more error code paste but I am also finding this issue in a PCL.
The only discrepancy between my own log and those posted is the line in InnerWeaver.cs at which the error is returned. I am getting line 164.
Rolling back to 1.51.3 removes the error, as noted by xalikoutis.

**Comment by distantcam** [comment]
@sebandraos That probably means you're using a different version of Fody, but it's the same issue.

**Comment by syaifulnizamyahya** [comment]
I have this error

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Object reference not set to an instance of an object.
StackTrace:
   at EqualityCheckWeaver.InjectEqualityCheck(Instruction targetInstruction, TypeReference targetType) in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 92
   at EqualityCheckWeaver.CheckAgainstField() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 39
   at EqualityCheckWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 32
   at ModuleWeaver.ProcessTypes(List`1 notifyNodes) in C:\projects\propertychanged\PropertyChanged.Fody\TypeProcessor.cs:line 38
   at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 43
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
PropertyChanged.Fody
TargetSite:
Void InjectEqualityCheck(Mono.Cecil.Cil.Instruction, Mono.Cecil.TypeReference)	Mast			
`

What is the solution?

**Comment by syaifulnizamyahya** [comment]
I have narrow down the problem.

In this class

> 
> 	// Contains data for multiple access points
> 	//[ImplementPropertyChanged]
> 	public class AccessPointCollection
> 	{
> 		ObservableCollection<AccessPointInfo> _accessPointsCollections = new ObservableCollection<AccessPointInfo>();
> 		DateTime _timeScanned = new DateTime();
> 		double _latitude;
> 		double _longitude;
> 		double _accuracy;
> 		DateTimeOffset _timeStamp = new DateTimeOffset();
> 		TimeSpan _duration = new TimeSpan();
> 
> 		public ObservableCollection<AccessPointInfo> AccessPointsCollections
> 		{
> 			get
> 			{
> 				return _accessPointsCollections;
> 			}
> 
> 			set
> 			{
> 				_accessPointsCollections = value;
> 			}
> 		}
> 
> 		public DateTime TimeScanned
> 		{
> 			get
> 			{
> 				return _timeScanned;
> 			}
> 
> 			set
> 			{
> 				_timeScanned = value;
> 			}
> 		}
> 
> 		public double Latitude
> 		{
> 			get
> 			{
> 				return _latitude;
> 			}
> 
> 			set
> 			{
> 				_latitude = value;
> 			}
> 		}
> 
> 		public double Longitude
> 		{
> 			get
> 			{
> 				return _longitude;
> 			}
> 
> 			set
> 			{
> 				_longitude = value;
> 			}
> 		}
> 
> 		public double Accuracy
> 		{
> 			get
> 			{
> 				return _accuracy;
> 			}
> 
> 			set
> 			{
> 				_accuracy = value;
> 			}
> 		}
> 
> 		public DateTimeOffset TimeStamp
> 		{
> 			get
> 			{
> 				return _timeStamp;
> 			}
> 
> 			set
> 			{
> 				_timeStamp = value;
> 			}
> 		}
> 
> 		public TimeSpan Duration
> 		{
> 			get
> 			{
> 				return _duration;
> 			}
> 
> 			set
> 			{
> 				_duration = value;
> 			}
> 		}
> 
> 	}

Error will be generated if this line

> [ImplementPropertyChanged]

is uncomment.

Whats the problem?
