### ISSUE TITLE
New version crashes when using generic type property with operator overload

### ISSUE THREAD

**Issue by davidroth** [Fody/PropertyChanged#259]
The current version (tested 2.1.2) crashes when using a generic type property with operator overload, where the generic base type is defined in another project.
```csharp
// This leads to the crash, if a concrete type is used, there is no crash
public BaseType<int> SomeProperty { get; set; }
```

```
Error Fody: An unhandled exception occurred:
Exception:
Member 'Corelib.BaseType`1' is declared in another module and needs to be imported
```
IMHO this is a regression introduced by  https://github.com/Fody/PropertyChanged/pull/164  in 1.5.2

I have created the following minimal repro:

**Assembly 1: "Corelib" (Contains the generic base type)**
```csharp
public abstract class BaseType<T> : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

   // If these overloads are removed, the crash is gone.
    public static bool operator ==(BaseType<T> first, BaseType<T> second) => false;
    public static bool operator !=(BaseType<T> first, BaseType<T> second) => false;
}
```

**Assembly 2: "ConsoleApp" (References to Corelib)**
```csharp
public class ViewModel : INotifyPropertyChanged
{
    // This leads to the crash, if a concrete type is used, there is no crash
    public BaseType<int> SomeProperty { get; set; }

    public event PropertyChangedEventHandler PropertyChanged;
}
```
When compiling i get the following crash:

```Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Member 'Corelib.BaseType`1' is declared in another module and needs to be imported
StackTrace:
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   at Mono.Cecil.SignatureWriter.WriteMethodSignature(IMethodSignature method)
   at Mono.Cecil.MetadataBuilder.GetMemberRefSignature(MemberReference member)
   at Mono.Cecil.MetadataBuilder.CreateMemberRefRow(MemberReference member)
   at Mono.Cecil.MetadataBuilder.GetMemberRefToken(MemberReference member)
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 89
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.MetadataToken LookupToken(Mono.Cecil.IMetadataTokenProvider)	Fody-Test			
```

**Comment by davidroth** [comment]
I have created a repro project for this issue: https://github.com/davidroth/fody-crash-259
