### ISSUE TITLE
Broken in .NET Standard F# projects

### ISSUE THREAD

**Issue by cmeeren** [Fody/PropertyChanged#292]
Repro:

1. Open VS 15.5 Preview 4 (15.5 needed for .NET Standard support in F# projects - might be able to repro with VS Code or using other build methods, I haven't tested)
2. Create a .NET Standard F# project
3. Add reference to PropertyChanged.Fody
4. Add FodyWeavers.xml with `PropertyChanged`
5. Build

I get this stack trace:

```
1>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>  Fody: Fody (version 2.0.0.0) Executing
1>    Fody/PropertyChanged:   	No reference to 'PropertyChanged' found. References not modified.
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Object reference not set to an instance of an object.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddLocalConstants(ScopeDebugInformation scope)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddLocalScope(MethodDebugInformation method_info, ScopeDebugInformation scope)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethodDebugInformation(MethodDebugInformation method_info)
1>MSBUILD : error :    at Mono.Cecil.Cil.PortablePdbWriter.Write(MethodDebugInformation info)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteUnresolvedMethodBody(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddTypes()
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildTypes()
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildModule()
1>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__1_0(MetadataBuilder builder, MetadataReader _)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>MSBUILD : error :    at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 86
1>MSBUILD : error : Source:
1>MSBUILD : error : Mono.Cecil
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void AddLocalConstants(Mono.Cecil.Cil.ScopeDebugInformation)
1>MSBUILD : error :
1>  Fody:   Finished Fody 604ms.
1>Done building project "ClassLibrary1.fsproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

```

**Comment by SimonCropp** [comment]
can u try with the latest version of fody

**Comment by SimonCropp** [comment]
ok this seems to fixed with the newest cecil that ships with fody. so i will deploy a new nuget with a higher dependency so it doesn't bite anyone else

**Comment by cmeeren** [comment]
Works, thanks.
