### ISSUE TITLE
Tests won't pass

### ISSUE THREAD

**Issue by worldbeater** [Fody/PropertyChanged#355]
Bad things happen when I clone the repo and try to run tests:

```
Stack trace:
   at Fody.PeVerifier.ThrowIfDifferent(String beforeAssemblyPath, String afterAssemblyPath, IEnumerable`1 ignoreCodes, String workingDirectory)
   at Fody.WeaverTestHelper.ExecuteTestRun(BaseModuleWeaver weaver, String assemblyPath, Boolean runPeVerify, Action`1 afterExecuteCallback, Action`1 beforeExecuteCallback, String assemblyName, IEnumerable`1 ignoreCodes)
   at AssemblyWithBaseInDifferentModuleTests.Weave(Boolean useStaticEqualsFromBase) in C:\Users\prizr\Documents\GitHub\PropertyChanged\Tests\AssemblyWithBaseInDifferentModuleTests.cs:line 13
   at AssemblyWithBaseInDifferentModuleTests.GenericChildClass() in C:\Users\prizr\Documents\GitHub\PropertyChanged\Tests\AssemblyWithBaseInDifferentModuleTests.cs:line 27
[xUnit.net 00:00:03.45]     AssemblyWithBaseInDifferentModuleTests.SimpleChildClass [FAIL]
[xUnit.net 00:00:03.64]     AssemblyWithBaseInDifferentModuleTests.GenericBase_OwnStaticEquals [FAIL]
[xUnit.net 00:00:03.87]     AssemblyWithBaseInDifferentModuleTests.GenericBase_StaticEquals_BaseNotUsed [FAIL]
[xUnit.net 00:00:04.09]     AssemblyWithBaseInDifferentModuleTests.GenericEquals [FAIL]
[xUnit.net 00:00:04.34]     AssemblyWithBaseInDifferentModuleTests.GenericBase_MultipleBaseClasses_GenericArgsMapping_BaseHasMoreArgs [FAIL]
[xUnit.net 00:00:04.59]     AssemblyWithBaseInDifferentModuleTests.DirectChildClass [FAIL]
Not passed:  AssemblyWithBaseInDifferentModuleTests.SimpleChildClass
Error message:
 System.Exception : The files have difference peverify results.
```

So, 29 tests fail, 94 tests pass, total 123.
Are the tests supposed to fail or am I doing something wrong?
Unable to contribute, help needed 🥇

**Comment by SimonCropp** [comment]
there should be more info in that stack trace https://github.com/Fody/Fody/blob/master/FodyHelpers/Testing/PeVerifier.cs#L81

**Comment by SimonCropp** [comment]
ok this is weird. i now get the same errors. my guess would be something to do with a changes new netcore sdk. it still passes on the build server.  i will look into it further.

in the short term if u want to get unstuck u can pass `runPeVerify:false` to the test runners

eg

```
        testResult = weavingTask.ExecuteTestRun("AssemblyWithTypeFilter.dll",runPeVerify:false);
```

**Comment by SimonCropp** [comment]
@worldbeater can u pull down the latest and try running the tests again

**Comment by worldbeater** [comment]
@SimonCropp the issue persists.

**Comment by worldbeater** [comment]
Yeah. `dotnet --version` returns `2.1.400` for me and I get the same errors when run https://github.com/Fody/PropertyChanged/commit/8c0e27fb335015224165552df88fdc90e477bb67

**Comment by SimonCropp** [comment]
can u try it on a different machine?

**Comment by worldbeater** [comment]
Tried on a different Windows machine, the issue was gone. 
So perhaps something is wrong with my installed tooling.
